language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo "Entered install..."
  - "pip install -r requirements.txt"

before_script:
  - echo "Entered before_script..."
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS process2;'

# command to run tests, e.g. python setup.py test
script:
  - python processUnitTest.py