language: python

python:
  - "2.7"

install:
  - echo "Entered install..."
  - "pip install -r requirements.txt"
  - pip install coveralls

before_script:
  - echo "Entered before_script..."
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS projecttest;'


script:
  - echo "Entered script..."
  - coverage run --source=processUnitTest.py
  - python processUnitTest.py

after_success:
  - coveralls

after_script:
  pip install scrutinizer-ocular
  ocular --data-file ".coverage" --config-file ".coveragerc"

after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*