language: python

python:
  - "2.7"

install:
  - echo "Entered install..."
  - "pip install -r requirements.txt"

before_script:
  - echo "Entered before_script..."
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS process2;'


script:
  - python processUnitTest.py